import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { PREPOSITION_IDS } from "../src/data/prepositions/shared/order";

function toModuleName(id: string) {
  return `${id
    .split("-")
    .map((part, index) =>
      index === 0 ? part : `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`,
    )
    .join("")}Module`;
}

const imports = PREPOSITION_IDS.map(
  (id) => `import ${toModuleName(id)} from "../${id}";`,
).join("\n");

const modules = PREPOSITION_IDS.map((id) => `  ${toModuleName(id)},`).join("\n");

const fileContent = `// Auto-generated by scripts/generate-preposition-registry.ts
// Do not edit this file manually. Update shared/order.ts and rerun the generator.

import type { PrepositionModule } from "./types";

${imports}

export const PREPOSITION_MODULES: PrepositionModule[] = [
${modules}
];
`;

writeFileSync(
  join(process.cwd(), "src/data/prepositions/shared/registry.ts"),
  fileContent,
);
