// Auto-generated by scripts/generate-preposition-registry.ts
// Do not edit this file manually. Update shared/order.ts and rerun the generator.

import type { PrepositionModule } from "./types";

import inModule from "../in";
import onModule from "../on";
import underModule from "../under";
import overModule from "../over";
import aboveModule from "../above";
import belowModule from "../below";
import besideModule from "../beside";
import nextToModule from "../next-to";
import nearModule from "../near";
import byModule from "../by";
import behindModule from "../behind";
import inFrontOfModule from "../in-front-of";
import betweenModule from "../between";
import amongModule from "../among";
import aroundModule from "../around";
import aboutModule from "../about";
import insideModule from "../inside";
import outsideModule from "../outside";
import acrossModule from "../across";
import throughModule from "../through";
import againstModule from "../against";
import alongModule from "../along";
import intoModule from "../into";
import ontoModule from "../onto";
import outOfModule from "../out-of";
import atModule from "../at";
import afterModule from "../after";
import toModule from "../to";
import fromModule from "../from";
import upModule from "../up";
import downModule from "../down";
import offModule from "../off";
import beneathModule from "../beneath";
import underneathModule from "../underneath";
import withinModule from "../within";
import withoutModule from "../without";
import pastModule from "../past";
import towardModule from "../toward";
import acrossFromModule from "../across-from";
import oppositeModule from "../opposite";
import throughoutModule from "../throughout";
import amidModule from "../amid";
import amidstModule from "../amidst";
import alongsideModule from "../alongside";
import beyondModule from "../beyond";
import uponModule from "../upon";
import onTopOfModule from "../on-top-of";
import inTheMiddleOfModule from "../in-the-middle-of";
import inBackOfModule from "../in-back-of";
import aheadOfModule from "../ahead-of";
import closeToModule from "../close-to";
import farFromModule from "../far-from";

export const PREPOSITION_MODULES: PrepositionModule[] = [
  inModule,
  onModule,
  underModule,
  overModule,
  aboveModule,
  belowModule,
  besideModule,
  nextToModule,
  nearModule,
  byModule,
  behindModule,
  inFrontOfModule,
  betweenModule,
  amongModule,
  aroundModule,
  aboutModule,
  insideModule,
  outsideModule,
  acrossModule,
  throughModule,
  againstModule,
  alongModule,
  intoModule,
  ontoModule,
  outOfModule,
  atModule,
  afterModule,
  toModule,
  fromModule,
  upModule,
  downModule,
  offModule,
  beneathModule,
  underneathModule,
  withinModule,
  withoutModule,
  pastModule,
  towardModule,
  acrossFromModule,
  oppositeModule,
  throughoutModule,
  amidModule,
  amidstModule,
  alongsideModule,
  beyondModule,
  uponModule,
  onTopOfModule,
  inTheMiddleOfModule,
  inBackOfModule,
  aheadOfModule,
  closeToModule,
  farFromModule,
];
